### ISSUE TITLE
function type of supportsGroup changed in MoveIt core 

### ISSUE THREAD

**Issue by SHTseng** [davetcoleman/moveit_whole_body_ik#2]
Hi, 
It seems that the function supportsGroup in moveit_core has changed. 
Compiler shows conflicting return type while building this project, after changing the function to
 `bool supportsGroup(const moveit::core::JointModelGroup *jmg, std::string* error_text_out = NULL) const;`, The build was successes.

**Comment by davetcoleman** [comment]
You're probably right. If you figure out a solution please share!

**Comment by davetcoleman** [comment]
Fixed for Kinetic: https://github.com/davetcoleman/moveit_whole_body_ik/commit/92e7664fa9abce2410e3cad84dd63409664d6865
